### ISSUE TITLE
是否缺少下单、物流接口？

### ISSUE THREAD

**Issue by sunkangchina** [javareact/alibaba-open#2]

**Comment by wechat-ok** [comment]
这里有下单的接口
src/functions/order/Order.php

物流查询在这里
[https://raw.githubusercontent.com/javareact/alibaba-open/master/src/functions/order/Logistics.php](https://raw.githubusercontent.com/javareact/alibaba-open/master/src/functions/order/Logistics.php)

**Comment by sunkangchina** [comment]
感谢，
